/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jma' at '3/22/16 3:39 PM' with Gradle 2.9
 *
 * @author jma, @date 3/22/16 3:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
